### ISSUE TITLE
Redo the codecov config as soon as tarpaulin is able to check the coverage on every line

### ISSUE THREAD

**Issue by 1c3t3a** [1c3t3a/rust-socketio#45]
Currently [tarpaulin](https://github.com/xd009642/tarpaulin) has some issues detecting dangling or formatted lines, see [#351](https://github.com/xd009642/tarpaulin/issues/351). This lead to some issues in #44 where the diff target was hit. I reconfigured the CI to shut up, but we should change it back as soon as tarpaulin is stable. The old config looked like this:

```yml
coverage: 
    status:
      project:
        default:        
          target: auto
          threshold: 2%
          paths:
             - "src"
         branches:
           - main
         if_ci_failed: ignore
         informational: false
         only_pulls: false
```
